# == In this configuration, you set up Alchemy's element layouts.
#
# For further information please see http://guides.alchemy-cms.com/stable/elements.html

- name: headline
  contents:
    - name: headline_name
      type: EssenceText
- name: text
  contents:
    - name: text_content
      type: EssenceRichtext
- name: pictures
  nestable_elements:
  - picture
- name: picture
  contents:
    - name: picture_content
      type: EssencePicture
