# == In this configuration, you set up Alchemy's element layouts.
#
# For further information please see https://alchemy-cms.com/docs/guides/elements

- name: headline
  ingredients:
    - role: headline_name
      type: Text
- name: text
  ingredients:
    - role: text_content
      type: Richtext
- name: pictures
  nestable_elements:
    - picture
- name: picture
  ingredients:
    - role: picture_content
      type: Picture
