# == This file defines the page layouts for new pages.
#
# For further information please see http://guides.alchemy-cms.com/stable/page_layouts.html

- name: index
  unique: true
  elements: [headline, pictures, text]
  autogenerate: [headline, text]
- name: scene
  elements: [headline, pictures, text]
  autogenerate: [headline, text]
  tags: true
