default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DOCKER_DB_HOST'] %>
  port: <%= ENV['DOCKER_DB_PORT'] %>

development:
  <<: *default
  database: dm-adventure-book_development
  username: admin
  password: dmadventurebook

test:
  <<: *default
  database: dm-adventure-book_test
  username: admin
  password: dmadventurebook
